import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RailSense",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Main container for the whole page, stacking vertically */}
        <div className="relative flex flex-col min-h-screen">
          <Navbar />
          
          {/* New container for the sidebar and main content, side-by-side */}
          <div className="flex flex-1">
            <div><Sidebar /></div>
          
            
            <main className="flex-1 p-8"> {/* Add padding here */}
              {children}
            </main>
          </div>
       

        </div>
      </body>
    </html>
  );
}